name: test

on:
  push:
  workflow_dispatch:

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:          
      - name: Run tests
        run: |
          echo tests
          mkdir foo
          cd foo
          pwd
          
      - name: Check cwd
        run: |
          pwd 
      
  deploy:
    uses: ./.github/workflows/deploy.yml
      
